### ISSUE TITLE
CF integration

### ISSUE THREAD

**Issue by contolini** [sebworks/AtomicComponent#1]
@sebworks I'm thinking we should keep this repo separate from CF. It's exceptionally well abstracted and stands fine on its own. CF can just inherit from it. I imagine you had this in mind when you wrote it. I propose we:
1. Move this repo to `cfpb/atomic-component`.
2. Publish it to npm as `atomic-component`.
3. Have CF organisms, molecules and atoms inherit from `atomic-component`.

For example, the code in [`table.js`](https://github.com/sebworks/AtomicComponent/blob/master/components/organisms/table.js) would be moved into [`cf-tables.js`](https://github.com/cfpb/capital-framework/blob/canary/src/cf-tables/src/cf-tables.js) and instead of importing

```
var closest = require( '../../utilities/dom-closest' ).closest;
var config = require( '../../utilities/config' );
var Organism = require( './Organism' );
```

at the top of the file, it'd be

```
var closest = require( 'atomic-component/utils/dom-closest' ).closest;
var config = require( 'atomic-component/utils/config' );
var Organism = require( 'atomic-component/organism' );
```

Here's the [complete example](https://github.com/cfpb/capital-framework/compare/prerelease-ver-4...atomic-inheritance?expand=1). I updated my [cf sandbox to use it](https://github.com/jimmynotjim/capital-framework-sandbox/compare/gh-pages...contolini:gh-pages#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21):

```
git clone git@github.com:contolini/capital-framework-sandbox.git
cd capital-framework-sandbox
npm i && npm start
```

Open http://localhost:3000/components/cf-tables/ and the table at the bottom should properly sort.

Let's chat later today!

cc @KimberlyMunoz @jimmynotjim @virginiacc @mistergone @cfarm

**Comment by sebworks** [comment]
@contolini thanks, this is great.

**Comment by KimberlyMunoz** [comment]
> I'm thinking we should keep this repo separate from CF. It's exceptionally well abstracted and stands fine on its own. 

I'm down. This also allows people to prototype stuff outside of Capital Framework which is nice, but it's nice to have two perspectives on this. 👍

**Comment by contolini** [comment]
@KimberlyMunoz the rationale there is that CF should be as lean as possible and _only_ contain CF-specific stuff. This is different from our previous strategy where we had CF-specific stuff spread across a dozen repos, resulting in maintenance overhead.

This repo is a mini atomic design framework that has nothing to do with CF. We might even want to namespace it in npm with an `@atomic` scope or something. `var molecule = require('@atomic/molecule')`

**Comment by jimmynotjim** [comment]
Sounds good to me.

**Comment by mistergone** [comment]
I missed this thread initially, but (for what it's worth) I totally support this approach!

❤️ this work.

**Comment by sebworks** [comment]
ok, I'm going to close this issue as I've migrated the code to https://github.com/cfpb/AtomicComponent and opened a PR https://github.com/cfpb/capital-framework/pull/396
